"""Tools for the Assets Generator agent."""

import base64
import json
from pathlib import Path

from google.adk.tools import ToolContext

PROJECT_ROOT = Path(__file__).parent.parent.parent
OUTPUT_DIR = PROJECT_ROOT / "output"


def load_ideas(tool_context: ToolContext) -> str:
    """Retrieves the post ideas generated by the ideation agent.

    Returns:
        The post ideas as a JSON string.
    """
    from agents.shared.schemas import STATE_KEY_IDEAS

    ideas = tool_context.state.get(STATE_KEY_IDEAS)
    if ideas:
        return json.dumps(ideas, indent=2)

    # Fallback: read from filesystem for standalone/manual runs
    fallback_path = PROJECT_ROOT / "output" / "ideas.json"
    with open(fallback_path) as f:
        return f.read()


def save_asset(image_base64: str, idea_id: str, version: int) -> str:
    """Saves a generated image asset to the output directory.

    Args:
        image_base64: Base64-encoded PNG image data.
        idea_id: The ID of the post idea this image is for.
        version: Version number of this image variation (1, 2, or 3).

    Returns:
        Confirmation message with the saved file path.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{idea_id}_v{version}.png"
    output_path = OUTPUT_DIR / filename

    image_bytes = base64.b64decode(image_base64)
    with open(output_path, "wb") as f:
        f.write(image_bytes)

    return f"Saved image to {output_path} ({len(image_bytes)} bytes)"
